### ISSUE TITLE
RY_KEY_CALLBACK_CFG

### ISSUE THREAD

**Issue by ascii33** [L231/ry_key#1]
RY_KEY_CALLBACK_CFG没这宏定义

**Comment by L231** [comment]
谢谢你的反馈。😂后面调整了名称，例程忘记同步调整了。
新的回调函数注册是：RY_KEY_SET_EVENT_HANDLER


有问题可以直接在公众号后台反馈，我会及时查看。







---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月05日 16:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [L231/ry_key] RY_KEY_CALLBACK_CFG (Issue #1) |

没这宏定义
